config/urls.py
# ruff: noqa
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include
from django.urls import path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("game.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("dashboard/", include("game.dashboards.urls")),
    path("items/", include("game.items.urls")),
    path("messaging/", include("game.messaging.urls")),
    # ...
    # Media files
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

game/items/urls.py
from django.urls import path

from game.items.views import itemslist

app_name = "items"

urlpatterns = [
    path("", itemslist, name="list"),
]

game/messaging/urls.py
from django.urls import path

from game.messaging.views import input_chat
from game.messaging.views import minimize_chat
from game.messaging.views import open_chat
from game.messaging.views import start_chat
from game.messaging.views import toggle_messages_box

app_name = "messaging"

urlpatterns = [
    path("start-chat/<slug:receiver_username>/", view=start_chat, name="start-chat"),
    path("open-chat/<slug:conversation_slug>/", view=open_chat, name="open-chat"),
    path(
        "minimize-chat/<slug:conversation_slug>/",
        view=minimize_chat,
        name="mini-chat",
    ),
    path("toggle-message-box/", view=toggle_messages_box, name="messages-toggle"),
    path("chat-input/<slug:conversation_slug>/", view=input_chat, name="chat-input"),
]

game/users/urls.py
from django.urls import path

from .views import user_detail_view
from .views import user_redirect_view
from .views import user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

game/items/models.py
import uuid

from django.db import models
from django.utils import timezone
from django.utils.text import slugify

from game.sets.models import Set
from game.utils.model_utils import handle_model_image
from game.utils.options import TYPE_OPTIONS


class Item(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    slug = models.SlugField(max_length=255, unique=True, editable=False)

    image = models.ImageField(upload_to="items/", null=True, blank=True)
    tag = models.CharField(max_length=120)
    name = models.CharField(max_length=120)
    description = models.CharField(max_length=220)
    info = models.CharField(max_length=220, blank=True)
    value = models.IntegerField(default=0)
    rarity = models.IntegerField(default=0)
    probability = models.DecimalField(default=1.0, decimal_places=4, max_digits=6)
    set = models.ForeignKey(Set, on_delete=models.CASCADE, related_name="items")
    control_number = models.PositiveIntegerField(default=0)
    sellable = models.BooleanField(default=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.name)

    def save(self, *args, **kwargs):
        self.updated_at = timezone.now()
        self.slug = slugify(str(self.uuid))
        if not self.created_at:
            self.created_at = timezone.now()

        super().save(*args, **kwargs)

        handle_model_image(self.image)


class ConsumableBaseItem(Item):
    health = models.PositiveIntegerField(default=0)
    experience = models.PositiveIntegerField(default=0)


class SlugConsumableBaseItem(Item):
    health = models.PositiveIntegerField(default=0)
    experience = models.PositiveIntegerField(default=0)
    revive = models.BooleanField(default=False, null=True, blank=True)


class ChestBaseItem(Item):
    probability_weight = models.DecimalField(
        default=1.0,
        decimal_places=4,
        max_digits=6,
    )
    min_items = models.PositiveIntegerField(default=2)
    max_items = models.PositiveIntegerField(default=5)
    monster_guarantee = models.PositiveIntegerField(default=0)
    exclude_consumables = models.BooleanField(default=False)
    exclude_currency = models.BooleanField(default=False)
    exclude_moves = models.BooleanField(default=False)
    exclude_monsters = models.BooleanField(default=False)
    exclude_wearables = models.BooleanField(default=False)
    exclude_collectables = models.BooleanField(default=False)
    exclude_chests = models.BooleanField(default=False)
    exclude_slugup = models.BooleanField(default=False)
    exclude_slugconsumable = models.BooleanField(default=False)


class WearableBaseItem(Item):
    WEARABLE_TYPES = [
        ("show", "show"),
        ("offense", "offense"),
        ("defense", "defense"),
    ]
    type = models.CharField(max_length=20, choices=TYPE_OPTIONS)
    wearable_type = models.CharField(
        max_length=20,
        choices=WEARABLE_TYPES,
        default="show",
    )
    health = models.PositiveIntegerField(default=0)
    attack = models.PositiveIntegerField(default=0)
    sp_attack = models.PositiveIntegerField(default=0)
    defense = models.PositiveIntegerField(default=0)
    sp_defense = models.PositiveIntegerField(default=0)
    speed = models.PositiveIntegerField(default=0)
    evasion = models.PositiveIntegerField(default=0)
    accuracy = models.PositiveIntegerField(default=0)


class CurrencyBaseItem(Item):
    min = models.PositiveIntegerField(default=10)
    max = models.PositiveIntegerField(default=50)


class SlugBaseItem(Item):
    pass


class CollectableBaseItem(Item):
    pass


class SlugUpBaseItem(Item):
    attack = models.IntegerField(default=0)
    sp_attack = models.IntegerField(default=0)
    defense = models.IntegerField(default=0)
    sp_defense = models.IntegerField(default=0)
    speed = models.IntegerField(default=0)
    evasion = models.IntegerField(default=0)
    accuracy = models.IntegerField(default=0)


class MoveBaseItem(Item):
    damage = models.PositiveIntegerField(default=0)
    total_pp = models.PositiveIntegerField(default=0)
    type_1 = models.CharField(max_length=20, choices=TYPE_OPTIONS)
    type_2 = models.CharField(max_length=20, choices=TYPE_OPTIONS)
    effect_1_chance = models.DecimalField(default=1.0, decimal_places=4, max_digits=6)
    effect_2_chance = models.DecimalField(default=1.0, decimal_places=4, max_digits=6)

game/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.utils.translation import gettext_lazy as _

from .models import User


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):  # type: ignore[name-defined]
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):  # type: ignore[name-defined]
        model = User
        error_messages = {
            "username": {"unique": _("This username has already been taken.")},
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

game/dashboards/views.py
from django.shortcuts import render


def dashboard(request):
    dashboard = request.user.dashboard

    context = {
        "page_title": "Dashboard",
        "dashboard": dashboard,
    }
    return render(request, "dashboard/dashboard.html", context)


def wallet(request):
    wallet = request.user.dashboard.wallet

    context = {
        "page_title": "Wallet",
        "wallet": wallet,
    }
    return render(request, "dashboard/wallet.html", context)


# HTMX ENDPOINTS


## HTMX NOTIFICATION ENDPOINTS
def clear_notification_indicator(request):
    unread_notifications = request.user.dashboard.notifications.filter(read=False)
    for notification in unread_notifications:
        notification.read = True
        notification.save()

    context = {
        "user": request.user,
    }

    return render(request, "snippets/notification-indicator.html", context)


## HTMX ANNOUNCEMENT ENDPOINTS
def clear_announcement_indicator(request):
    unread_announcements = request.user.dashboard.announcements.filter(read=False)
    for announcement in unread_announcements:
        announcement.read = True
        announcement.save()

    context = {
        "user": request.user,
    }

    return render(request, "snippets/announcement-indicator.html", context)

game/items/views.py
from django.shortcuts import render

from game.items.models import Item


def itemslist(request):
    items = Item.objects.all()
    return render(
        request,
        "items/items_list.html",
        {"items": items},
    )

game/messaging/views.py
import logging

from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer
from django.contrib.auth import get_user_model
from django.http.response import HttpResponse
from django.shortcuts import render
from django.template import RequestContext
from django.template import Template
from django.template.loader import render_to_string

from game.dashboards.models import Dashboard
from game.messaging.models import Conversation
from game.messaging.models import ConversationControls
from game.messaging.models import Message

User = get_user_model()

logger = logging.getLogger(__name__)


def chat_generator(request, dashboard):
    # Render the conversation panel and chat list templates
    conversations_panel = render_to_string(
        "snippets/chat/conversations-panel.html",
        {"open_conversations": dashboard.get_open_conversations()},
        request,
    )
    chats_list = render_to_string(
        "snippets/chat/chats-list.html",
        {"conversations": dashboard.get_conversations()},
        request,
    )

    # Combine the HTML and render
    bulk_html = chats_list + conversations_panel
    debug_message = f"Bulk HTML generated: {bulk_html}"
    logger.debug(debug_message)

    template = Template(bulk_html)
    context = RequestContext(request)
    return HttpResponse(template.render(context))


def toggle_messages_box(request):
    if request.method == "POST":
        dashboard = Dashboard.objects.get(user=request.user)
        if dashboard.messages_open:
            show_messages = False
            dashboard.messages_open = False
        else:
            show_messages = True
            dashboard.messages_open = True
        dashboard.save()

        context = {
            "show_messages": show_messages,
            "conversations": dashboard.conversations,
            "open_conversations": dashboard.get_open_conversations(),
        }

        return render(request, "snippets/chatbar.html", context)
    return HttpResponse()


def start_chat(request, receiver_username):
    if request.method == "POST":
        receiver = User.objects.get(username=receiver_username)
        debug_message = f"Receiver fetched: {receiver}"
        logger.debug(debug_message)

        # Create a new conversation
        conversation = Conversation.objects.create(
            name=f"{receiver.username}, {request.user.username}",
        )
        debug_message = f"Conversation created: {conversation}"
        logger.debug(debug_message)

        # Add members to the conversation
        conversation.members.add(receiver.dashboard)
        ConversationControls.objects.create(
            conversation=conversation,
            owner=receiver.dashboard,
        )
        conversation.members.add(request.user.dashboard)
        ConversationControls.objects.create(
            open=True,
            conversation=conversation,
            owner=request.user.dashboard,
        )
        debug_message = f"Members added to conversation: {conversation.members.all()}"
        logger.debug(debug_message)

        return chat_generator(request, request.user.dashboard)
    return HttpResponse()


def open_chat(request, conversation_slug):
    if request.method in ["POST", "DELETE"]:
        conversation = Conversation.objects.get(slug=conversation_slug)
        controls = ConversationControls.objects.get(
            conversation=conversation,
            owner=request.user.dashboard,
        )
        if controls.open:
            controls.open = False
        else:
            controls.open = True
            controls.minimized = False
        controls.save()

        return chat_generator(request, request.user.dashboard)
    return HttpResponse()


def minimize_chat(request, conversation_slug):
    if request.method == "POST":
        conversation = Conversation.objects.get(slug=conversation_slug)
        controls = ConversationControls.objects.get(
            conversation=conversation,
            owner=request.user.dashboard,
        )
        if controls.minimized:
            controls.minimized = False
        else:
            controls.minimized = True
        controls.save()
        return chat_generator(request, request.user.dashboard)
    return HttpResponse()


def input_chat(request, conversation_slug):
    if request.method == "POST":
        conversation = Conversation.objects.get(slug=conversation_slug)
        chat_input = request.POST.get("chat-input")
        message = Message.objects.create(
            conversation=conversation,
            sender=request.user.dashboard,
            message=chat_input,
        )

        channel_layer = get_channel_layer()
        async_to_sync(channel_layer.group_send)(
            f"group_{conversation.slug}",
            {
                "type": "message.dispatch",
                "message_slug": message.slug,
                "conversation_slug": conversation_slug,
            },
        )

    return HttpResponse()

game/sets/views.py
# Create your views here.

game/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView
from django.views.generic import RedirectView
from django.views.generic import UpdateView

from game.users.models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        # for mypy to know that the user is authenticated
        assert self.request.user.is_authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

game/templates/snippets/chat/chats-list.html
<div id="chat-list-container" hx-swap-oob="true">
  <div class="chats-list">
    <div class="chats-list-title d-flex justify-content-between">
      Messages
      <a href="#"
         hx-post="{% url 'messaging:messages-toggle' %}"
         hx-trigger="click"
         hx-swap="outerHTML"
         hx-target="closest #chatbar"
         class="btn btn-sm btn-secondary"><i class="fa-solid fa-square-xmark"></i></a>
    </div>
    <ul class="chats-list-ul list-group">
      {% if conversations|length %}
        {% for conversation in conversations %}
          <li hx-post="{% url 'messaging:open-chat' conversation_slug=conversation.slug %}"
              hx-trigger="click"
              hx-swap="outerHTML"
              class="list-group-item d-flex rounded-6">
            <div class="chat-list-avatar">
              <img src="https://variety.com/wp-content/uploads/2023/05/spider-2.jpg?w=1000"
                   alt="#" />
            </div>
            <div class="col chat-list-info">
              <div class="d-flex justify-content-between">
                <h5>{{ conversation.slug }}</h5>
                <p>3 days ago</p>
              </div>
              <p>last message preview text...</p>
            </div>
          </li>
        {% endfor %}
      {% else %}
        <li class="list-group-item d-flex rounded-6">
          <div class="col chat-list-info">
            <p class="text-muted text-center">
              <em>no conversations. start one!</em>
            </p>
          </div>
        </li>
      {% endif %}
    </ul>
  </div>
</div>

game/templates/snippets/chat/conversations-panel.html
{% load chat_tags %}

<div id="chatbar-conversations"
     class="chatbar-conversations d-flex align-items-end"
     hx-swap-oob="true">
  {% for conversation in open_conversations %}
    {% chat_minimized_check conversation request.user.dashboard as is_minimized %}
    <div id="chatbar-conv-1"
         class="{% if is_minimized %}minimized {% endif %}chatbar-conversation">
      <div class="conv-title d-flex  justify-content-between align-items-center">
        <div class="chat-list-avatar">
          <img src="https://variety.com/wp-content/uploads/2023/05/spider-2.jpg?w=1000"
               alt="#" />
        </div>
        <div class="col chat-list-info">
          <div class="d-flex justify-content-between">
            <h5>{% chat_name conversation request.user %}</h5>
            <p>{% chat_time conversation.message.last %}</p>
            <span>
              <a href="#"
                 hx-post="{% url 'messaging:mini-chat' conversation_slug=conversation.slug %}"
                 hx-trigger="click"
                 hx-swap="outerHTML">
                <i class="fa-solid fa-minus"></i>
              </a>
              <a href="#"
                 hx-delete="{% url 'messaging:open-chat' conversation_slug=conversation.slug %}"
                 hx-trigger="click"
                 hx-swap="outerHTML"><i class="fa-solid fa-square-xmark"></i></a>
            </span>
          </div>
        </div>
      </div>
      <div id="chat-messages-ws-{{ conversation.slug }}"
           hx-ext="ws"
           ws-connect="/ws/chat/{{ conversation.slug }}/"
           hx-swap="beforeend"
           hx-target="#messages-{{ conversation.slug }}">
        {% include "snippets/chat/messages-box.html" with user=user conversation=conversation messages=conversation.messages.all %}
      </div>
      <div id="chatbar-form-1" class="chatbar-form">
        <form id="convo-form-{{ conversation.slug }}"
              hx-post="{% url 'messaging:chat-input' conversation_slug=conversation.slug %}"
              hx-trigger="submit"
              hx-swap="none"
              class="chat-form d-flex">
          <textarea name="chat-input"
                    class="col"
                    placeholder="enter message..."
                    hx-trigger="keydown.enter"></textarea>
          <button class="btn btn-primary" type="submit">
            <i class="fa-solid fa-paper-plane"></i>
          </button>
        </form>
      </div>
    </div>
  {% endfor %}
</div>

game/templates/snippets/chat/message.html
<div id="message-{{ message.slug }}"
     class="chat-message {% if message.sender == user.dashboard or message_context == 'sender' %}sent{% else %}received{% endif %}">
  <span><small>{{ message.created_at }}</small></span>
  <div class="chat-message-wrapper">
    <p>{{ message.message }}</p>
  </div>
</div>

game/templates/snippets/chat/messages-box.html
<div id="messages-{{ conversation.slug }}" class="message-box">
  {% for message in messages %}
    {% include "snippets/chat/message.html" with user=user message=message %}
  {% endfor %}
</div>